#!/bin/bash
# nunect NATS Server Management Script
# Usage: ./nats-server.sh [start|stop|restart|status|ui|manage]

set -e

# =============================================================================
# Load Environment
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env"
CONFIG_DIR="$PROJECT_ROOT/config"
DATA_DIR="$PROJECT_ROOT/data/nats"
LOG_DIR="$PROJECT_ROOT/logs"
UI_DIR="$PROJECT_ROOT/web/nats-manager"
PID_FILE="$PROJECT_ROOT/.nats-server.pid"
UI_PID_FILE="$PROJECT_ROOT/.nats-ui.pid"
RUNTIME_CONFIG="$CONFIG_DIR/nats-server-runtime.conf"

# Check for .env file
if [ ! -f "$ENV_FILE" ]; then
    echo "ERROR: .env file not found at $ENV_FILE"
    echo "Copy .env.template to .env and customize:"
    echo "  cp .env.template .env"
    exit 1
fi

# Source .env (export all variables)
set -a
source "$ENV_FILE"
set +a

# =============================================================================
# Helper Functions
# =============================================================================

is_running() {
    local pid_file=$1
    if [ -f "$pid_file" ]; then
        local pid=$(cat "$pid_file" 2>/dev/null)
        if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
            return 0
        fi
    fi
    return 1
}

# Parse actual values from runtime config
get_config_value() {
    local key=$1
    if [ -f "$RUNTIME_CONFIG" ]; then
        grep "^${key}:" "$RUNTIME_CONFIG" | head -1 | sed 's/.*: *//' | tr -d '"'
    fi
}

# Get actual server info from running server
get_server_info() {
    local var=$1
    local https_port=$(get_config_value "https_port")
    if [ -n "$https_port" ]; then
        curl -s -k "https://localhost:${https_port}/varz" 2>/dev/null | grep -o "\"${var}\":\"[^\"]*\"" | cut -d'"' -f4
    fi
}

# =============================================================================
# Start NATS Server
# =============================================================================

cmd_start() {
    if is_running "$PID_FILE"; then
        echo "NATS server is already running (PID: $(cat $PID_FILE))"
        if ! is_running "$UI_PID_FILE"; then
            echo ""
            echo "UI server is NOT running. Start it with:"
            echo "  ./scripts/nats-server.sh ui"
        fi
        return 0
    fi
    
    # Check if port is already in use
    if lsof -i :${NATS_PORT} > /dev/null 2>&1; then
        echo "WARNING: Port ${NATS_PORT} is already in use."
        echo "Killing existing process..."
        lsof -i :${NATS_PORT} | grep -v COMMAND | awk '{print $2}' | xargs kill 2>/dev/null || true
        sleep 1
    fi
    
    # Create directories
    mkdir -p "$DATA_DIR"
    mkdir -p "$LOG_DIR"
    mkdir -p "$CONFIG_DIR/certs"
    
    # Validate TLS certificates exist
    if [ ! -f "$NATS_TLS_CERT" ] || [ ! -f "$NATS_TLS_KEY" ]; then
        echo "ERROR: TLS certificates not found:"
        echo "  Cert: $NATS_TLS_CERT"
        echo "  Key:  $NATS_TLS_KEY"
        echo ""
        echo "Set paths in .env to your system-managed certificates:"
        echo "  NATS_TLS_CERT=/etc/ssl/certs/your-cert.pem"
        echo "  NATS_TLS_KEY=/etc/ssl/private/your-key.key"
        exit 1
    fi
    
    # Generate runtime config
    CONFIG_TEMPLATE="$CONFIG_DIR/nats-server.conf"
    if [ ! -f "$CONFIG_TEMPLATE" ]; then
        echo "ERROR: Config template not found at $CONFIG_TEMPLATE"
        exit 1
    fi
    
    # Generate runtime config from template
    echo "# Generated by nats-server.sh at $(date)" > "$RUNTIME_CONFIG"
    echo "# DO NOT EDIT - This file is regenerated on each start" >> "$RUNTIME_CONFIG"
    echo "" >> "$RUNTIME_CONFIG"
    envsubst < "$CONFIG_TEMPLATE" >> "$RUNTIME_CONFIG"
    
    # Check for nats-server
    if ! command -v nats-server &> /dev/null; then
        echo "ERROR: nats-server not found in PATH"
        echo "Install: go install github.com/nats-io/nats-server/v2@latest"
        exit 1
    fi
    
    # Get actual values that will be used
    ACTUAL_PORT=$(get_config_value "port")
    ACTUAL_HTTPS_PORT=$(get_config_value "https_port")
    ACTUAL_WS_PORT=$(grep -A2 "^websocket {" "$RUNTIME_CONFIG" | grep "port:" | head -1 | sed 's/.*: *//' | tr -d ' ')
    
    echo "Starting nunect NATS Server..."
    echo "  Config: $RUNTIME_CONFIG"
    echo "  Data:   $DATA_DIR"
    echo "  Logs:   $LOG_DIR"
    if [ "${NATS_MANAGER_DOMAIN}" != "localhost" ]; then
        echo "  NATS:   nats://${NATS_MANAGER_DOMAIN}:${ACTUAL_PORT}"
        [ -n "$ACTUAL_HTTPS_PORT" ] && echo "  HTTPS:  https://${NATS_MANAGER_DOMAIN}:${ACTUAL_HTTPS_PORT}"
        [ -n "$ACTUAL_WS_PORT" ] && echo "  WSS:    wss://${NATS_WS_DOMAIN:-${NATS_MANAGER_DOMAIN}}:${ACTUAL_WS_PORT}"
    else
        echo "  NATS:   nats://localhost:${ACTUAL_PORT}"
        [ -n "$ACTUAL_HTTPS_PORT" ] && echo "  HTTPS:  https://localhost:${ACTUAL_HTTPS_PORT}"
        [ -n "$ACTUAL_WS_PORT" ] && echo "  WSS:    wss://localhost:${ACTUAL_WS_PORT}"
    fi
    echo ""
    
    # Start in background, redirect to log file
    nohup nats-server -c "$RUNTIME_CONFIG" >> "$LOG_DIR/nats-server.log" 2>&1 &
    echo $! > "$PID_FILE"
    
    # Wait a moment and check if started
    sleep 1
    if is_running "$PID_FILE"; then
        echo "NATS server started (PID: $(cat $PID_FILE))"
        echo "View logs: tail -f $LOG_DIR/nats-server.log"
    else
        echo "ERROR: NATS server failed to start"
        exit 1
    fi
}

# =============================================================================
# Stop NATS Server
# =============================================================================

cmd_stop() {
    if is_running "$PID_FILE"; then
        local pid=$(cat "$PID_FILE")
        echo "Stopping NATS server (PID: $pid)..."
        kill "$pid" 2>/dev/null || true
        rm -f "$PID_FILE"
        echo "NATS server stopped"
    else
        echo "NATS server is not running"
    fi
}

# =============================================================================
# Restart NATS Server
# =============================================================================

cmd_restart() {
    cmd_stop
    sleep 1
    cmd_start
}

# =============================================================================
# Status Check
# =============================================================================

cmd_status() {
    echo "=== nunect NATS Status ==="
    echo ""
    
    # Get actual values from runtime config
    ACTUAL_PORT=$(get_config_value "port" 2>/dev/null)
    ACTUAL_HTTPS_PORT=$(get_config_value "https_port" 2>/dev/null)
    
    # NATS Server
    if is_running "$PID_FILE"; then
        local pid=$(cat "$PID_FILE")
        echo "NATS Server: RUNNING (PID: $pid)"
        echo "  Config: $RUNTIME_CONFIG"
        
        # Get actual values from running server if possible
        local server_name=$(get_server_info "server_name" 2>/dev/null)
        local server_port=$(get_server_info "port" 2>/dev/null)
        
        if [ -n "$server_name" ]; then
            echo "  Name:   $server_name"
        fi
        if [ -n "$ACTUAL_PORT" ]; then
            echo "  Port:   $ACTUAL_PORT (client connections)"
        fi
        if [ -n "$ACTUAL_HTTPS_PORT" ]; then
            echo "  HTTPS:  https://localhost:${ACTUAL_HTTPS_PORT}"
        fi
        
        # Try to get connection count
        if [ -n "$ACTUAL_HTTPS_PORT" ]; then
            local conns=$(curl -s -k "https://localhost:${ACTUAL_HTTPS_PORT}/connz" 2>/dev/null | grep -o '"num_connections":[0-9]*' | cut -d: -f2)
            echo "  Connections: ${conns:-unknown}"
        fi
    else
        echo "NATS Server: STOPPED"
    fi
    
    echo ""
    
    # UI Server
    if is_running "$UI_PID_FILE"; then
        local ui_pid=$(cat "$UI_PID_FILE")
        echo "UI Server:   RUNNING (PID: $ui_pid)"
        echo "  Port:   ${NATS_MANAGER_PORT}"
        echo "  Bind:   ${NATS_MANAGER_BIND}"
        echo "  Domain: ${NATS_MANAGER_DOMAIN}"
        if [ "${NATS_MANAGER_DOMAIN}" != "localhost" ]; then
            echo "  URL:    https://${NATS_MANAGER_DOMAIN}:${NATS_MANAGER_PORT}"
        else
            echo "  URL:    https://localhost:${NATS_MANAGER_PORT}"
        fi
    else
        echo "UI Server:   STOPPED"
    fi
    
    echo ""
    echo "Commands:"
    echo "  ./scripts/nats-server.sh start   - Start NATS server"
    echo "  ./scripts/nats-server.sh stop    - Stop NATS server"
    echo "  ./scripts/nats-server.sh ui      - Start UI server"
    echo "  ./scripts/nats-server.sh manage  - Start both"
    echo "  ./scripts/nats-server.sh status  - Show this status"
}

# =============================================================================
# Start UI Server
# =============================================================================

cmd_ui() {
    if is_running "$UI_PID_FILE"; then
        echo "UI server is already running (PID: $(cat $UI_PID_FILE))"
        if [ "${NATS_MANAGER_DOMAIN}" != "localhost" ]; then
            echo "Access at: https://${NATS_MANAGER_DOMAIN}:${NATS_MANAGER_PORT}"
        else
            echo "Access at: https://localhost:${NATS_MANAGER_PORT}"
        fi
        return 0
    fi
    
    # Check if port is already in use (stale process)
    if lsof -i :${NATS_MANAGER_PORT} > /dev/null 2>&1; then
        echo "WARNING: Port ${NATS_MANAGER_PORT} is already in use."
        echo "Killing existing process on port ${NATS_MANAGER_PORT}..."
        lsof -i :${NATS_MANAGER_PORT} | grep -v COMMAND | awk '{print $2}' | xargs kill 2>/dev/null || true
        sleep 1
    fi
    
    if [ ! -f "$UI_DIR/server.py" ]; then
        echo "ERROR: UI server not found at $UI_DIR/server.py"
        exit 1
    fi
    
    echo "Starting nunect NATS Manager UI..."
    echo "  Port:   ${NATS_MANAGER_PORT}"
    echo "  Bind:   ${NATS_MANAGER_BIND}"
    echo "  Domain: ${NATS_MANAGER_DOMAIN}"
    echo "  CORS:   ${NATS_MANAGER_CORS_ORIGINS}"
    echo ""
    
    nohup python3 "$UI_DIR/server.py" >> "$PROJECT_ROOT/logs/nats-ui.log" 2>&1 &
    echo $! > "$UI_PID_FILE"
    
    sleep 1
    if is_running "$UI_PID_FILE"; then
        echo "UI server started (PID: $(cat $UI_PID_FILE))"
        if [ "${NATS_MANAGER_DOMAIN}" != "localhost" ]; then
            echo "Access at: https://${NATS_MANAGER_DOMAIN}:${NATS_MANAGER_PORT}"
        else
            echo "Access at: https://localhost:${NATS_MANAGER_PORT}"
        fi
    else
        echo "ERROR: UI server failed to start"
        exit 1
    fi
}

# =============================================================================
# Stop UI Server
# =============================================================================

cmd_ui_stop() {
    if is_running "$UI_PID_FILE"; then
        local pid=$(cat "$UI_PID_FILE")
        echo "Stopping UI server (PID: $pid)..."
        kill "$pid" 2>/dev/null || true
        rm -f "$UI_PID_FILE"
        echo "UI server stopped"
    fi
}

# =============================================================================
# Start Both (Manage)
# =============================================================================

cmd_manage() {
    cmd_start
    echo ""
    cmd_ui
    echo ""
    
    # Get actual values from runtime config
    ACTUAL_HTTPS_PORT=$(get_config_value "https_port" 2>/dev/null)
    ACTUAL_WS_PORT=$(grep -A2 "^websocket {" "$RUNTIME_CONFIG" 2>/dev/null | grep "port:" | head -1 | sed 's/.*: *//' | tr -d ' ')
    
    echo "=== Both services started ==="
    if [ "${NATS_MANAGER_DOMAIN}" != "localhost" ]; then
        [ -n "$ACTUAL_HTTPS_PORT" ] && echo "NATS: https://${NATS_MANAGER_DOMAIN}:${ACTUAL_HTTPS_PORT}"
        echo "UI:   https://${NATS_MANAGER_DOMAIN}:${NATS_MANAGER_PORT}"
        [ -n "$ACTUAL_WS_PORT" ] && echo "WSS:  wss://${NATS_WS_DOMAIN:-${NATS_MANAGER_DOMAIN}}:${ACTUAL_WS_PORT}"
    else
        [ -n "$ACTUAL_HTTPS_PORT" ] && echo "NATS: https://localhost:${ACTUAL_HTTPS_PORT}"
        echo "UI:   https://localhost:${NATS_MANAGER_PORT}"
        [ -n "$ACTUAL_WS_PORT" ] && echo "WSS:  wss://localhost:${ACTUAL_WS_PORT}"
    fi
}

# =============================================================================
# Stop All
# =============================================================================

cmd_stop_all() {
    cmd_ui_stop
    cmd_stop
}

# =============================================================================
# Main Command Dispatch
# =============================================================================

COMMAND=${1:-status}

case "$COMMAND" in
    start)
        cmd_start
        ;;
    stop)
        cmd_stop_all
        ;;
    restart)
        cmd_restart
        ;;
    status)
        cmd_status
        ;;
    ui)
        cmd_ui
        ;;
    ui-stop)
        cmd_ui_stop
        ;;
    manage)
        cmd_manage
        ;;
    *)
        echo "Usage: $0 [start|stop|restart|status|ui|ui-stop|manage]"
        echo ""
        echo "Commands:"
        echo "  start      Start NATS server"
        echo "  stop       Stop all services (NATS + UI)"
        echo "  restart    Restart NATS server"
        echo "  status     Show status of all services"
        echo "  ui         Start UI server only"
        echo "  ui-stop    Stop UI server only"
        echo "  manage     Start both NATS server and UI"
        exit 1
        ;;
esac
